# Maintainer: Antoni Zasada
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=audioleaf-bin
pkgver=1.0.3
pkgrel=1
pkgdesc="Visualize music on your Nanoleaf Canvas"
url="https://github.com/alfazet/audioleaf"
license=("MIT")
arch=("x86_64")
provides=("audioleaf")
conflicts=("audioleaf")
source=("https://github.com/alfazet/audioleaf/releases/download/v$pkgver/audioleaf-$pkgver-x86_64.tar.gz")
sha256sums=("0f8b2d47ae62be64bed294e8aa09b0c42873cbee065211c9d7385b6a045ddae7")

package() {
    install -Dm755 audioleaf -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
